
image: "rust:latest"


stages:
  - check
  - test
  - publish
  - post-run


clean-code:
  stage: check
  script:
    - rustup component add rustfmt-preview
    - cargo fmt --all -- --check
  allow_failure: true

check:
  stage: check
  script:
    - cargo check

unittests:
  stage: test
  script:
    - cargo test --release

benchmarktests:
  stage: test
  script:
    - cargo bench

cratesio:
  stage: publish
  script:
    - rm -r -f files
    - cargo login $CARGO_LOGIN
    - cargo package
    - cargo publish
  when: on_success
  only:
    refs:
      - stable
  allow_failure: true

clippy:
  stage: post-run
  script:
    - rustup default nightly
    - rustup update
    - rustup component add clippy-preview
    - cargo clippy -- -D clippy::pedantic
  allow_failure: true